<div class="pull-left">
    <p>
    <h2>All Tickets</h2>
    <p/>
</div>
<div class="pull-right">
    <a class="btn btn-default" href="<?= $this->url(array('controller' => 'ticket', 'action' => 'json'), 'default', true) ?>"><i class="fa fa-code"></i> Json Export(Restfull)</a>
    <a class="btn btn-default" href="<?= $this->url(array('controller' => 'ticket', 'action' => 'csv'), 'default', true) ?>"><i class="fa fa-file-excel-o"></i> Csv Export</a>
</div>
<table class="table table-striped table-responsive table-bordered table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>id</th>
        <th>Title</th>
        <th>Detail</th>
        <th width="50">Priority</th>
        <th width="20">Attachment</th>
        <th width="150">Created</th>
        <th width="100"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->tickets as $ticket): ?>
        <tr>
            <td><?= $index + 1; ?></td>
            <td><?= $ticket->id ?></td>
            <td><?= $this->escape($ticket->title) ?></td>
            <td title="<?= $this->escape($ticket->detail) ?>" onclick="alert(this.title);"><?= substr($this->escape($ticket->detail), 0, 150); ?>...</td>
            <td><?= $ticket->priority; ?></td>
            <td><a title="<?= $ticket->attachment; ?>" target="_blank" href="<?= $this->baseUrl() . "/upload/" . $ticket->attachment; ?>"><i class="fa fa-download "></i></a></td>
            <td><?= $ticket->created; ?></td>
            <td><a class="btn btn-default deletelink" href="<?= $this->url(array('controller' => 'ticket', 'action' => 'delete', 'id' => $ticket->id), 'default', true) ?>"><i class="fa fa-trash"></i> Delete</a></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<p class="recordinfo">
    <?php
    echo count($this->tickets) == 0 ? "No record found" : count($this->tickets) . " records found";
    ?>
</p>
