<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>ZF 1 Ticket</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <?php echo $this->headLink()->appendStylesheet('/zendticket/public/css/global.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    <?php echo $this->headLink()->appendStylesheet('css/global.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo" style="float: left">
        <b>ZF 1 Ticket</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(array('controller' => 'ticket'), 'default', true) ?>">All Tickets</a>
        -
        <a href="<?php echo $this->url(array('controller' => 'ticket', 'action' => 'add'), 'default', true) ?>">Add New Ticket</a>
    </div>
</div>
<p>
    <?php
    if ($this->messages) {
        foreach ($this->messages as $msg) {
            echo '<div class="alert alert-info" role="alert">' . $msg . '</div>';
        }
    } ?>
</p>
<?php echo $this->layout()->content ?>

<script src="https://use.fontawesome.com/250347bee8.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>